import { defineBuildConfig } from 'unbuild';

import {
  mkdirSync,
  writeFileSync,
} from 'node:fs';

import {
  join,
} from 'pathe';

import {
  type ThemeOptions,
  defaultPrimaryColor,
  makeThemeFromPartialOptions,
  formatTheme,
} from './src/theme/index';

const themes: Record<string, Partial<ThemeOptions<string>>> = {
  style: {
    colors: {
      primary: defaultPrimaryColor,
    },
    omitTheme: true,
  },
};

function writeTheme<K extends string>(dirname: string, filename: string, themeOptions: Partial<ThemeOptions<K>>) {
  const theme = makeThemeFromPartialOptions(themeOptions);
  const [indent, newLine] = ['  ', '\n'];

  const chunks = formatTheme(theme, 'class', indent, newLine);
  const content = [
    '/* This file is auto-generated by @poupe/tailwindcss. DO NOT EDIT */',
    newLine, newLine,
    ...chunks,
  ].join('');

  const destdir = join(process.cwd(), dirname);
  mkdirSync(destdir, { recursive: true });
  writeFileSync(join(destdir, filename), content);
  console.log(`[writeTheme] Wrote ${content.length} bytes to ${join(dirname, filename)}`);
}

export default defineBuildConfig({
  entries: [
    { input: 'src/index', name: 'index' },
    { input: 'src/theme/index', name: 'theme' },
    { input: 'src/utils/index', name: 'utils' },
    { input: 'src/assets', name: 'assets', builder: 'copy' },
  ],
  declaration: true,
  sourcemap: true,

  hooks: {
    'build:prepare'() {
      // assemble assets
      for (const [filename, themeOptions] of Object.entries(themes)) {
        writeTheme('src/assets', `${filename}.css`, themeOptions);
      }
    },
  },
});
