import { addTemplate, addVitePlugin } from '@nuxt/kit';
import tailwindPlugin from '@tailwindcss/vite';

import { contentGlobs } from '@poupe/vue/config';
import { makeThemeFromPartialOptions, formatTheme } from '@poupe/tailwindcss/theme';
import { type CSSProperties, formatCSSProperties } from '@poupe/css';

import type { ModuleOptions } from './config';
import { createDefaultResolver } from './utils';

const TAILWIND_CSS_FILENAME = 'tailwind.css';

export type Plugin = string | [ string, CSSProperties ];

export const formatPlugin = (plugin: Plugin, indent: string = '  '): string[] => {
  if (typeof plugin === 'string') {
    return [`@plugin '${plugin}'`];
  }

  const [name, props] = plugin;
  const lines = formatCSSProperties(props);

  if (lines.length === 0)
    return [`@plugin '${name}'`];

  return [
    `@plugin '${name}' {`,
    ...lines.map(line => `${indent}${line};`),
    '}',
  ];
};

/** generate the content of the `tailwind.css` file */
const getCSSContent = (
  options: ModuleOptions,
  sources: string[] = [],
  plugins: Plugin[] = [],
  resolve: (...path: string[]) => string = createDefaultResolver(),
): string => {
  const content = [
    // @poupe/vue
    ...contentGlobs(),

    // extra files to scan
    ...sources.map(source => resolve(source)),
  ];

  // generate theme
  const theme = makeThemeFromPartialOptions(options.theme);

  // generate content for the `tailwind.css` file embedding
  // the poupe theme
  const lines: string[] = [
    '/* This file is generated by @poupe/nuxt. DO NOT EDIT */',
    '',
    '@import \'tailwindcss\'',
    '',
    // @theme
    formatTheme(theme).join(''),
    // @plugin
    ...(plugins ? ['', ...plugins.flatMap(plugin => formatPlugin(plugin))] : []),

    // @source
    ...(content ? ['', ...content.map(path => `@source '${path}';`)] : []),
  ];

  return lines.join('\n');
};

export const installTailwindPlugin = async (
  options: ModuleOptions,
  sources: string[] = [],
  plugins: string[] = [],
  resolve: (...path: string[]) => string = createDefaultResolver(),
) => {
  // tailwind.css
  addTemplate({
    filename: TAILWIND_CSS_FILENAME,
    getContents: () => getCSSContent(options, sources, plugins, resolve),
  });

  // vite plugin
  addVitePlugin(tailwindPlugin());
};
